# Generated by Django 5.0.4 on 2024-04-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descriptin',
            new_name='description',
        ),
    ]
